-- Consumable cards (Tarot / Planet) stored outside the deck.
-- Tarot metadata:
--   select = { exact = N } or { min = a, max = b } ("at least" style when min/max).
--   spawn = { kind = "tarot"|"planet", count = k } — adds up to k items, limited by free slots after use.
--   spawn_joker = true — needs a free Joker slot.
--   wheel_of_fortune = true — needs ≥1 owned Joker.
--   fool_duplicate = true — duplicates last used Tarot/Planet this run (not Fool).
-- `atlas` must exist in `Game.ASSET_ATLAS`. Major arcana `index` matches typical 0..21 sheet order.

CONSUMABLE_DEFS = {
    tarot_fool = {
        id = "tarot_fool",
        kind = "tarot",
        name = "The Fool",
        sell_cost = 3,
        atlas = "Tarot",
        index = 0,
        fool_duplicate = true,
        select = { exact = 0 },
        tooltip = {
            "Creates the last Tarot or Planet card used during this run.",
            "The Fool excluded",
        },
    },
    tarot_magician = {
        id = "tarot_magician",
        kind = "tarot",
        name = "The Magician",
        sell_cost = 4,
        atlas = "Tarot",
        index = 1,
        select = { exact = 2 },
        tooltip = "Enhances 2 selected cards to Lucky Cards",
    },
    tarot_high_priestess = {
        id = "tarot_high_priestess",
        kind = "tarot",
        name = "The High Priestess",
        sell_cost = 4,
        atlas = "Tarot",
        index = 2,
        spawn = { kind = "planet", count = 2 },
        select = { exact = 0 },
        tooltip = {
            "Creates up to 2 random Planet cards.",
            "(Must have room)",
        },
    },
    tarot_empress = {
        id = "tarot_empress",
        kind = "tarot",
        name = "The Empress",
        sell_cost = 4,
        atlas = "Tarot",
        index = 3,
        select = { exact = 2 },
        tooltip = "Enhances 2 selected cards to Mult Cards",
    },
    tarot_emperor = {
        id = "tarot_emperor",
        kind = "tarot",
        name = "The Emperor",
        sell_cost = 4,
        atlas = "Tarot",
        index = 4,
        spawn = { kind = "tarot", count = 2 },
        select = { exact = 0 },
        tooltip = {
            "Creates up to 2 random Tarot cards.",
            "(Must have room)",
        },
    },
    tarot_hierophant = {
        id = "tarot_hierophant",
        kind = "tarot",
        name = "The Hierophant",
        sell_cost = 4,
        atlas = "Tarot",
        index = 5,
        select = { exact = 2 },
        tooltip = "Enhances 2 selected cards to Bonus Cards",
    },
    tarot_lovers = {
        id = "tarot_lovers",
        kind = "tarot",
        name = "The Lovers",
        sell_cost = 4,
        atlas = "Tarot",
        index = 6,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Wild Card",
    },
    tarot_chariot = {
        id = "tarot_chariot",
        kind = "tarot",
        name = "The Chariot",
        sell_cost = 4,
        atlas = "Tarot",
        index = 7,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Steel Card",
    },
    tarot_strength = {
        id = "tarot_strength",
        kind = "tarot",
        name = "Strength",
        sell_cost = 4,
        atlas = "Tarot",
        index = 11,
        select = { min = 1, max = 2 },
        tooltip = "Increases rank of up to 2 selected cards by 1",
    },
    tarot_hermit = {
        id = "tarot_hermit",
        kind = "tarot",
        name = "The Hermit",
        sell_cost = 4,
        atlas = "Tarot",
        index = 9,
        select = { exact = 0 },
        hermit_money = true,
        tooltip = {
            "Doubles money.",
            "(Max of $20)",
        },
    },
    tarot_wheel_of_fortune = {
        id = "tarot_wheel_of_fortune",
        kind = "tarot",
        name = "Wheel of Fortune",
        sell_cost = 4,
        atlas = "Tarot",
        index = 10,
        wheel_of_fortune = true,
        select = { exact = 0 },
        tooltip = "1 in 4 chance to add Foil, Holographic, or Polychrome edition to a random Joker",
    },
    tarot_justice = {
        id = "tarot_justice",
        kind = "tarot",
        name = "Justice",
        sell_cost = 4,
        atlas = "Tarot",
        index = 8,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Glass Card",
    },
    tarot_hanged_man = {
        id = "tarot_hanged_man",
        kind = "tarot",
        name = "The Hanged Man",
        sell_cost = 4,
        atlas = "Tarot",
        index = 12,
        select = { min = 1, max = 2 },
        tooltip = "Destroys up to 2 selected cards",
    },
    tarot_death = {
        id = "tarot_death",
        kind = "tarot",
        name = "Death",
        sell_cost = 4,
        atlas = "Tarot",
        index = 13,
        select = { exact = 2 },
        tooltip = {
            "Select 2 cards, convert the left card into the right card.",
            "(Drag to rearrange)",
        },
    },
    tarot_temperance = {
        id = "tarot_temperance",
        kind = "tarot",
        name = "Temperance",
        sell_cost = 4,
        atlas = "Tarot",
        index = 14,
        select = { exact = 0 },
        temperance_money = true,
        tooltip = {
            "Gives the total sell value of all current Jokers.",
            "(Max of $50)",
        },
    },
    tarot_devil = {
        id = "tarot_devil",
        kind = "tarot",
        name = "The Devil",
        sell_cost = 4,
        atlas = "Tarot",
        index = 15,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Gold Card",
    },
    tarot_tower = {
        id = "tarot_tower",
        kind = "tarot",
        name = "The Tower",
        sell_cost = 4,
        atlas = "Tarot",
        index = 16,
        select = { exact = 1 },
        tooltip = "Enhances 1 selected card into a Stone Card",
    },
    tarot_star = {
        id = "tarot_star",
        kind = "tarot",
        name = "The Star",
        sell_cost = 4,
        atlas = "Tarot",
        index = 17,
        select = { min = 1, max = 3 },
        convert_suit = "Diamonds",
        tooltip = "Converts up to 3 selected cards to Diamonds",
    },
    tarot_moon = {
        id = "tarot_moon",
        kind = "tarot",
        name = "The Moon",
        sell_cost = 4,
        atlas = "Tarot",
        index = 18,
        select = { min = 1, max = 3 },
        convert_suit = "Clubs",
        tooltip = "Converts up to 3 selected cards to Clubs",
    },
    tarot_sun = {
        id = "tarot_sun",
        kind = "tarot",
        name = "The Sun",
        sell_cost = 4,
        atlas = "Tarot",
        index = 19,
        select = { min = 1, max = 3 },
        convert_suit = "Hearts",
        tooltip = "Converts up to 3 selected cards to Hearts",
    },
    tarot_world = {
        id = "tarot_world",
        kind = "tarot",
        name = "The World",
        sell_cost = 4,
        atlas = "Tarot",
        index = 21,
        select = { min = 1, max = 3 },
        convert_suit = "Spades",
        tooltip = "Converts up to 3 selected cards to Spades",
    },
    tarot_judgement = {
        id = "tarot_judgement",
        kind = "tarot",
        name = "Judgement",
        sell_cost = 4,
        atlas = "Tarot",
        index = 20,
        spawn_joker = true,
        select = { exact = 0 },
        tooltip = {
            "Creates a random Joker card.",
            "(Must have room)",
        },
    },
    planet_pluto = {
        id = "planet_pluto",
        kind = "planet",
        name = "Pluto",
        sell_cost = 3,
        atlas = "Planet",
        hand = "High Card",
        index = 29,
    },
    planet_mercury = {
        id = "planet_mercury",
        kind = "planet",
        name = "Mercury",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Pair",
        index = 30,
    },
    planet_uranus = {
        id = "planet_uranus",
        kind = "planet",
        name = "Uranus",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Two Pair",
        index = 36
    },
    planet_venus = {
        id = "planet_venus",
        kind = "planet",
        name = "Venus",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Three of a Kind",
        index = 31,
    },
    planet_saturn = {
        id = "planet_saturn",
        kind = "planet",
        name = "Saturn",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Straight",
        index = 35,
    },
    planet_neptune = {
        id = "planet_neptune",
        kind = "planet",
        name = "Neptune",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Straight Flush",
        index = 37,
    },
    planet_mars = {
        id = "planet_mars",
        kind = "planet",
        name = "Mars",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Four of a Kind",
        index = 33,
    },
    planet_jupiter = {
        id = "planet_jupiter",
        kind = "planet",
        name = "Jupiter",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Flush",
        index = 34,
    },
    planet_earth = {
        id = "planet_earth",
        kind = "planet",
        name = "Earth",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Full House",
        index = 32,
    },
    planet_ceres = {
        id = "planet_ceres",
        kind = "planet",
        name = "Ceres",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Flush House",
        index = 38,
    },
    planet_x = {
        id = "planet_x",
        kind = "planet",
        name = "Planet X",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Five of a Kind",
        index = 39,
    },
    planet_eris = {
        id = "planet_eris",
        kind = "planet",
        name = "Planet X",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Flush Five",
        index = 23
    }
}
