-- Consumable cards (Tarot / Planet) that are stored separately from the deck.
-- `atlas` values must exist in `Game.ASSET_ATLAS` (see `Game:set_render_settings`).
CONSUMABLE_DEFS = {
    tarot_fool = {
        id = "tarot_fool",
        kind = "tarot",
        name = "The Fool",
        sell_cost = 3,
        atlas = "Tarot",
        index = 0,
    },
    tarot_magician = {
        id = "tarot_magician",
        kind = "tarot",
        name = "The Magician",
        sell_cost = 4,
        atlas = "Tarot",
        index = 1,
    },
    planet_pluto = {
        id = "planet_pluto",
        kind = "planet",
        name = "Pluto",
        sell_cost = 3,
        atlas = "Planet",--Planet and Tarot is the same atlas
        hand = "High Card",
        index = 29,
    },
    planet_mercury = {
        id = "planet_mercury",
        kind = "planet",
        name = "Mercury",
        sell_cost = 3,
        atlas = "Planet", 
        hand = "Pair",
        index = 30,
    },
    planet_uranus = {
        id = "planet_uranus",
        kind = "planet",
        name = "Uranus",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Two Pair",
        index = 36
    },
    planet_venus = {
        id = "planet_venus",
        kind = "planet",
        name = "Venus",
        sell_cost = 3,
        atlas = "Planet", 
        hand = "Three of a Kind",
        index = 31,
    },
    planet_saturn = {
        id = "planet_saturn",
        kind = "planet",
        name = "Saturn",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Straight",
        index = 35,
    },
    planet_neptune = {
        id = "planet_neptune",
        kind = "planet",
        name = "Neptune",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Straight Flush",
        index = 37,
    },
    planet_mars = {
        id = "planet_mars",
        kind = "planet",
        name = "Mars",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Four of a Kind",
        index = 33,
    },
    planet_jupiter = {
        id = "planet_jupiter",
        kind = "planet",
        name = "Jupiter",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Flush",
        index = 34,
    },
    planet_earth = {
        id = "planet_earth",
        kind = "planet",
        name = "Earth",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Full House",
        index = 32,
    },
    planet_ceres = {
        id = "planet_ceres",
        kind = "planet",
        name = "Ceres",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Flush House",
        index = 38,
    },
    planet_x = {
        id = "planet_x",
        kind = "planet",
        name = "Planet X",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Five of a Kind",
        index = 39,
    },
    planet_eris = {
        id = "planet_eris",
        kind = "planet",
        name = "Planet X",
        sell_cost = 3,
        atlas = "Planet",
        hand = "Flush Five",
        index = 23
    }
}

